name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build Streamlit static files
        run: |
          mkdir -p build
          cp -r * build/ || true
          echo "<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv='refresh' content='0; url=https://share.streamlit.io/tingyuansen/arxiv_summary_viewer/main/app.py'>
            </head>
          </html>" > build/index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true