name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Clean and Build
        run: |
          rm -rf build
          mkdir -p build
          cp -r * build/ || true
          echo "<!DOCTYPE html>
          <html>
            <head>
              <title>ArXiv Summary Viewer</title>
              <meta http-equiv='refresh' content='0; url=https://tingyuansen-arxiv-summary-viewer-app-xxxxxxx.streamlit.app'>
            </head>
          </html>" > build/index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          cname: arxiv-summary-viewer.streamlit.app